name: microscopy-seg-track
channels:
  - conda-forge
dependencies:
  # add your dependencies below
  # pinning versions if necessary 
  - python=3.10.14
  - numpy
  - scipy
  - h5py
  # additionally, include these deps
  - ipywidgets
  - matplotlib
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
  - pandas
  - opencv
  - pillow
  - ipython
  - imageio
  - imageio-ffmpeg
